BigStore/Areas/Admin/Pages/Role/AddRoleClaim.cshtml.cs
using BigStore.DataAccess;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace BigStore.Areas.Admin.Pages.Role
{
    public class AddRoleClaim : RolePageModel
    {
        private readonly ApplicationDbContext _context;

        public AddRoleClaim(RoleManager<IdentityRole> roleManager, ApplicationDbContext context) : base(roleManager)
        {
            _context = context;
        }

        public class InputModel
        {
            [Required(ErrorMessage = "Phải nhập tên của đặc tính")]
            [Display(Name = "Tên của đặc tính (Claim)")]
            [StringLength(256, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string ClaimType { set; get; } = string.Empty;

            [Required(ErrorMessage = "Phải nhập giá trị của đặc tính")]
            [Display(Name = "Giá trị của đặc tính (Claim)")]
            [StringLength(256, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string ClaimValue { set; get; } = string.Empty;
        }

        [BindProperty]
        public InputModel Input { set; get; }

        public IdentityRole Role { get; set; }

        public async Task<IActionResult> OnGet(string roleid)
        {
            Role = await _roleManager.FindByIdAsync(roleid);
            if (Role == null)
                return NotFound("Không tìm thấy role");

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string roleid)
        {
            Role = await _roleManager.FindByIdAsync(roleid);
            if (Role == null) return NotFound("Không tìm thấy role");

            if (!ModelState.IsValid) return Page();

            if ((await _roleManager.GetClaimsAsync(Role)).Any(c => c.Type == Input.ClaimType && c.Value == Input.ClaimValue))
            {
                ModelState.AddModelError(string.Empty, "Claim này đã có trong role");
                return Page();
            }

            var newClaim = new Claim(Input.ClaimType, Input.ClaimValue);

            var result = await _roleManager.AddClaimAsync(Role, newClaim);

            if (!result.Succeeded)
            {
                result.Errors.ToList().ForEach(error =>
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
                return Page();
            }

            StatusMessage = "Vừa thêm đặc tính (claim) mới.";

            return RedirectToPage("./Edit", new { roleid });
        }
    }
}

BigStore/Areas/Admin/Pages/Role/AddUserRole.cshtml.cs
using BigStore.DataAccess;
using BigStore.BusinessObject;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BigStore.Areas.Admin.Pages.Role
{
    //[Authorize(Policy = "AllowEditRole")]
    public class AddUserRoleModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _context;

        public AddUserRoleModel(RoleManager<IdentityRole> roleManager,
                            UserManager<User> userManager,
                            ApplicationDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }

        public class InputModel
        {
            [Required]
            public string ID { set; get; }
            public string? Name { set; get; }

            public string[]? RoleNames { set; get; }
        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool isConfirmed { set; get; }

        [TempData] // Sử dụng Session
        public string StatusMessage { get; set; }

        public List<string> AllRoles { set; get; } = new List<string>();

        public List<IdentityRoleClaim<string>> ClaimInRoles { get; set; }
        public List<IdentityUserClaim<string>> ClaimInUsers { get; set; }

        public async Task<IActionResult> OnGetAsync(string userid)
        {
            if (string.IsNullOrEmpty(userid)) return NotFound("Không thấy user");

            var user = await _userManager.FindByIdAsync(userid);
            if (user == null) return NotFound("Không thấy user");

            var roles = await _userManager.GetRolesAsync(user);
            var allroles = await _roleManager.Roles.ToListAsync();

            allroles.ForEach((r) =>
            {
                AllRoles.Add(r.Name);
            });

            //get claim in role user have
            var listRoles = from r in _context.Roles
                            join ur in _context.UserRoles on r.Id equals ur.RoleId
                            where ur.UserId == user.Id
                            select r;

            var _claimInRole = from c in _context.RoleClaims
                               join r in listRoles on c.RoleId equals r.Id
                               select c;

            ClaimInRoles = await _claimInRole.ToListAsync();
            ClaimInUsers = await _context.UserClaims.Where(c => c.UserId == user.Id).ToListAsync();

            Input = new InputModel
            {
                ID = user.Id,
                Name = user.UserName,
                RoleNames = roles.ToArray()
            };

            Input.Name = user.UserName;

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var user = await _userManager.FindByIdAsync(Input.ID);
            if (user == null)
            {
                return NotFound("Không thấy user");
            }

            var roles = await _userManager.GetRolesAsync(user);
            var allroles = await _roleManager.Roles.ToListAsync();

            allroles.ForEach((r) =>
            {
                AllRoles.Add(r.Name);
            });

            //get claim in role user have
            var listRoles = from r in _context.Roles
                            join ur in _context.UserRoles on r.Id equals ur.RoleId
                            where ur.UserId == user.Id
                            select r;

            var _claimInRole = from c in _context.RoleClaims
                               join r in listRoles on c.RoleId equals r.Id
                               select c;

            ClaimInRoles = await _claimInRole.ToListAsync();
            ClaimInUsers = await _context.UserClaims.Where(c => c.UserId == user.Id).ToListAsync();

            if (!isConfirmed)
            {
                Input.RoleNames = roles.ToArray();
                isConfirmed = true;
                StatusMessage = "";
                ModelState.Clear();
            }
            else
            {
                // Update add and remove
                StatusMessage = "Vừa cập nhật";
                if (Input.RoleNames == null) Input.RoleNames = new string[] { };
                foreach (var rolename in Input.RoleNames)
                {
                    if (roles.Contains(rolename)) continue;
                    await _userManager.AddToRoleAsync(user, rolename);
                }
                foreach (var rolename in roles)
                {
                    if (Input.RoleNames.Contains(rolename)) continue;
                    await _userManager.RemoveFromRoleAsync(user, rolename);
                }

            }

            Input.Name = user.UserName;
            return Page();
        }
    }
}

BigStore/Areas/Admin/Pages/Role/EditRoleClaim.cshtml.cs
using BigStore.DataAccess;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace BigStore.Areas.Admin.Pages.Role
{
    public class EditRoleClaim : RolePageModel
    {
        private readonly ApplicationDbContext _context;

        public EditRoleClaim(RoleManager<IdentityRole> roleManager, ApplicationDbContext context) : base(roleManager)
        {
            _context = context;
        }

        public class InputModel
        {
            [Required(ErrorMessage = "Phải nhập tên của đặc tính")]
            [Display(Name = "Tên của đặc tính (Claim)")]
            [StringLength(256, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string ClaimType { set; get; } = string.Empty;

            [Required(ErrorMessage = "Phải nhập giá trị của đặc tính")]
            [Display(Name = "Giá trị của đặc tính (Claim)")]
            [StringLength(256, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string ClaimValue { set; get; } = string.Empty;
        }

        [BindProperty]
        public InputModel Input { set; get; }

        public IdentityRole Role { get; set; }

        public IdentityRoleClaim<string> Claim { get; set; }

        public async Task<IActionResult> OnGet(int? claimid)
        {
            if (claimid == null) return NotFound("không tìm thấy claim");

            Claim = await _context.RoleClaims.Where(c => c.Id == claimid).FirstOrDefaultAsync();
            if (Claim == null) return NotFound("không tìm thấy claim");

            Role = await _roleManager.FindByIdAsync(Claim.RoleId);
            if (Role == null) return NotFound("không tìm thấy role của claim");

            Input = new InputModel()
            {
                ClaimType = Claim.ClaimType,
                ClaimValue = Claim.ClaimValue
            };

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? claimid)
        {
            if (claimid == null) return NotFound("không tìm thấy claim");

            Claim = await _context.RoleClaims.Where(c => c.Id == claimid).FirstOrDefaultAsync();
            if (Claim == null) return NotFound("không tìm thấy claim");

            Role = await _roleManager.FindByIdAsync(Claim.RoleId);
            if (Role == null) return NotFound("không tìm thấy role của claim");

            if (!ModelState.IsValid) return Page();

            if (_context.RoleClaims.Any(c =>
                c.RoleId == Role.Id
                && c.ClaimType == Input.ClaimType
                && c.ClaimValue == Input.ClaimValue
                && c.Id != claimid))
            {
                ModelState.AddModelError(string.Empty, "Claim này đã có trong role");
            }

            Claim.ClaimType = Input.ClaimType;
            Claim.ClaimValue = Input.ClaimValue;

            await _context.SaveChangesAsync();

            StatusMessage = "Vừa cập nhật đặc tính (claim).";

            return RedirectToPage("./Edit", new { roleid = Role.Id });
        }

        public async Task<IActionResult> OnPostDeleteAsync(int? claimid)
        {
            if (claimid == null) return NotFound("không tìm thấy claim");

            Claim = await _context.RoleClaims.Where(c => c.Id == claimid).FirstOrDefaultAsync();
            if (Claim == null) return NotFound("không tìm thấy claim");

            Role = await _roleManager.FindByIdAsync(Claim.RoleId);
            if (Role == null) return NotFound("không tìm thấy role của claim");

            await _roleManager.RemoveClaimAsync(Role, new Claim(Claim.ClaimType, Claim.ClaimValue));
            await _context.SaveChangesAsync();

            StatusMessage = "Vừa xoá đặc tính (claim).";

            return RedirectToPage("./Edit", new { roleid = Role.Id });
        }
    }
}

BigStore/Areas/Admin/Pages/Role/EditUserRoleClaim.cshtml.cs
using BigStore.DataAccess;
using BigStore.BusinessObject;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace BigStore.Areas.Admin.Pages.Role
{
    public class EditUserRoleClaimModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _context;

        public EditUserRoleClaimModel(RoleManager<IdentityRole> roleManager,
                            UserManager<User> userManager,
                            ApplicationDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public NotFoundObjectResult OnGet() => NotFound("Không được truy cập");

        public class InputModel
        {
            [Required(ErrorMessage = "Phải nhập tên của đặc tính")]
            [Display(Name = "Tên của đặc tính (Claim)")]
            [StringLength(256, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string ClaimType { set; get; } = string.Empty;

            [Required(ErrorMessage = "Phải nhập giá trị của đặc tính")]
            [Display(Name = "Giá trị của đặc tính (Claim)")]
            [StringLength(256, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string ClaimValue { set; get; } = string.Empty;
        }

        [BindProperty] public InputModel Input { set; get; }
        public User User { get; set; }

        public async Task<IActionResult> OnGetAddClaimAsync(string userid)
        {
            User = await _userManager.FindByIdAsync(userid);
            if (User == null) return NotFound("Khong tim thay user");

            return Page();
        }

        public async Task<IActionResult> OnPostAddClaimAsync(string userid)
        {
            User = await _userManager.FindByIdAsync(userid);
            if (User == null) return NotFound("Khong tim thay user");

            if (!ModelState.IsValid) return Page();

            var claims = _context.UserClaims.Where(c => c.UserId == userid);
            if (claims.Any(c => c.ClaimType == Input.ClaimType && c.ClaimValue == Input.ClaimValue))
            {
                ModelState.AddModelError(string.Empty, "Đặc tính này đã có");
                return Page();
            }

            await _userManager.AddClaimAsync(User, new Claim(Input.ClaimType, Input.ClaimValue));
            StatusMessage = "Đã thêm đặc tính cho user";

            return Page();
        }

        public IdentityUserClaim<string> UserClaim { get; set; }

        public async Task<IActionResult> OnGetEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Khong tim thay claim");

            UserClaim = await _context.UserClaims.FirstOrDefaultAsync(c => c.Id == claimid);
            if (UserClaim == null) return NotFound("Không tìm thấy claim");

            User = await _userManager.FindByIdAsync(UserClaim.UserId);
            if (User == null) return NotFound("Khong tim thay user");

            Input = new InputModel
            {
                ClaimType = UserClaim.ClaimType,
                ClaimValue = UserClaim.ClaimValue
            };

            return Page();
        }

        public async Task<IActionResult> OnPostEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Khong tim thay claim");

            UserClaim = await _context.UserClaims.FirstOrDefaultAsync(c => c.Id == claimid);
            if (UserClaim == null) return NotFound("Không tìm thấy claim");

            User = await _userManager.FindByIdAsync(UserClaim.UserId);
            if (User == null) return NotFound("Khong tim thay user");

            if (!ModelState.IsValid) return Page();

            if ((await _context.UserClaims.AnyAsync(
                c => c.UserId == User.Id
                && c.Id != claimid
                && c.ClaimType == Input.ClaimType
                && c.ClaimValue == Input.ClaimValue)))
            {
                ModelState.AddModelError(string.Empty, "Đã tồn tại đặc tính này");
                return Page();
            }

            UserClaim.ClaimType = Input.ClaimType;
            UserClaim.ClaimValue = Input.ClaimValue;
            await _context.SaveChangesAsync();

            StatusMessage = "Đã cập nhật đặc tính cho user";
            return RedirectToPage("./AddUserRole", new { userid = User.Id });
        }

        public async Task<IActionResult> OnPostDeleteAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Khong tim thay claim");

            UserClaim = await _context.UserClaims.FirstOrDefaultAsync(c => c.Id == claimid);
            if (UserClaim == null) return NotFound("Không tìm thấy claim");

            User = await _userManager.FindByIdAsync(UserClaim.UserId);
            if (User == null) return NotFound("Khong tim thay user");

            await _userManager.RemoveClaimAsync(User, new Claim(UserClaim.ClaimType, UserClaim.ClaimValue));

            StatusMessage = "Đã xoá đặc tính cho user";
            return RedirectToPage("./AddUserRole", new { userid = User.Id });
        }
    }
}

BigStore/Areas/Admin/Pages/Role/AddRoleClaim.cshtml
@page "/admin/add-role-claim/{roleid}"
@model AddRoleClaim
@{
    ViewData["Title"] = "Gán đặc tính cho role";
}

<h4>@ViewData["Title"]: @Model.Role.Name</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimType"></label>
                <input asp-for="Input.ClaimType" class="form-control">
                <span asp-validation-for="Input.ClaimType" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimValue"></label>
                <input asp-for="Input.ClaimValue" class="form-control">
                <span asp-validation-for="Input.ClaimValue" class="text-danger"></span>
            </div>

            <input value="Tạo mới" type="submit" class="btn btn-primary"/>
                
            <a class="btn btn-primary" asp-page="./Create" asp-route-roleid="@Model.Role.Id">Chỉnh sửa role</a>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/AddUserRole.cshtml
@page "/admin/add-user-role/"
@model BigStore.Areas.Admin.Pages.Role.AddUserRoleModel
@{
   ViewData["Title"] = "Cập nhật role cho User";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Chọn các role gán cho <strong>@Model.Input.Name</strong></p>
        <form method="post">
            <partial name="_StatusMessage" model="@Model.StatusMessage" />
            <div class="form-group">
                @Html.LabelFor(x => x.Input.RoleNames)
                @Html.ListBoxFor(x => x.Input.RoleNames,
                    new SelectList( Model.AllRoles ),
                    new {@class="w-100", id = "selectrole"})
            </div>

            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden"  asp-for="Input.ID">
            <input type="hidden"  asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./User">Danh sách</a>
            <button type="submit" class="btn btn-danger">Cập nhật</button>
        </form>
        <hr />
        <p>Các claim của user có được từ role:</p>
        @if(Model.ClaimInRoles.Count > 0)
        {
            <ul>
                @foreach (var claim in Model.ClaimInRoles)
                {
                    <li>@claim.ClaimType: @claim.ClaimValue</li>
                }
            </ul>
        }
        <p>Các claim riêng của user:</p>
        <a asp-page="./EditUserRoleClaim" asp-page-handler="AddClaim" asp-route-userid="@Model.Input.ID" class="btn btn-primary">+ Thêm claim riêng</a>
        @if(Model.ClaimInUsers.Count > 0)
        {
            <ul>
                @foreach (var claim in Model.ClaimInUsers)
                {
                    <li>
                        <a asp-page="./EditUserRoleClaim" asp-page-handler="EditClaim" asp-route-claimid="@claim.Id">
                            @claim.ClaimType: @claim.ClaimValue
                        </a>
                    </li>
                }
            </ul>
        }
    </div>
</div>

@section Scripts {
    <script src="~/lib/multiple-select/multiple-select.min.js"></script>
    <link rel="stylesheet" href="~/lib/multiple-select/multiple-select.min.css" />
    <script>
          $('#selectrole').multipleSelect({
                selectAll: false,
                keepOpen: false,
                isOpen: false
            });
    </script>


    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/Create.cshtml
@page "/admin/role/add-role"
@model CreateModel
@{
    ViewData["Title"] = "Tạo mới role";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-2">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name" class="form-control">
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Thêm role</button>
                
            <a class="btn btn-primary" asp-page="./Index">Danh sách các role</a>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/Delete.cshtml
@page "/admin/role/delte-role/{roleid}"
@model BigStore.Areas.Admin.Pages.Role.DeleteModel
@{
   ViewData["Title"] = "Xóa role";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Bạn có chăc chắn xóa Role <strong>@Model.Input.Name</strong> </p>
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden"  asp-for="Input.ID">
            <a class="btn btn-primary" asp-page="./Index">Danh sách role</a>
            <button type="submit" class="btn btn-danger">Xóa</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/Edit.cshtml
@page "/admin/role/edit-role/{roleid}"
@model EditModel
@{
    ViewData["Title"] = "Cập nhật role";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-2">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name" class="form-control">
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Cập nhật role</button>
                
            <a class="btn btn-primary" asp-page="./Index">Danh sách các role</a>
        </form>
        <hr />
        <p>Các đặc tính (claim) của role: </p>
        <a class="btn btn-primary" asp-page="./AddRoleClaim" asp-route-roleid="@Model.Role.Id">+ Thêm claim</a>
        @if(Model.Claims?.Count > 0)
        {
            <ul>
                @foreach(var claim in Model.Claims)
                {
                    <li>
                        <a asp-page="./EditRoleClaim" asp-route-claimid="@claim.Id">@claim.ClaimType: @claim.ClaimValue</a> 
                    </li>
                }
            </ul>
        }
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/EditRoleClaim.cshtml
@page "/admin/edit-role-claim/{claimid}"
@model EditRoleClaim
@{
    ViewData["Title"] = "Chỉnh sửa đặc tính cho role";
}

<h4>@ViewData["Title"]: @Model.Role.Name</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimType"></label>
                <input asp-for="Input.ClaimType" class="form-control">
                <span asp-validation-for="Input.ClaimType" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimValue"></label>
                <input asp-for="Input.ClaimValue" class="form-control">
                <span asp-validation-for="Input.ClaimValue" class="text-danger"></span>
            </div>

            <input value="Cập nhật" type="submit" class="btn btn-primary"/>
            <input value="Xoá" type="submit" asp-page-handler="Delete" class="btn btn-danger"/>
                
            <a class="btn btn-primary" asp-page="./Create" asp-route-claimid="@Model.Claim.Id">Chỉnh sửa role</a>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/EditUserRoleClaim.cshtml
@page "/admin/edit-user-role-claim/"
@model BigStore.Areas.Admin.Pages.Role.EditUserRoleClaimModel
@{
   ViewData["Title"] = "Thêm claim cho User";
}

<h4>@ViewData["Title"]: @Model.User.UserName</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimType"></label>
                <input asp-for="Input.ClaimType" class="form-control">
                <span asp-validation-for="Input.ClaimType" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Input.ClaimValue"></label>
                <input asp-for="Input.ClaimValue" class="form-control">
                <span asp-validation-for="Input.ClaimValue" class="text-danger"></span>
            </div>
            @if (Model.UserClaim is null)
            {
                <input value="Tạo mới" type="submit" class="btn btn-primary"/>
            }
            else
            {
                <input value="Cập nhật" type="submit" class="btn btn-primary"/>
                <input value="Xoá" type="submit" class="btn btn-danger" asp-route-claimid="@Model.UserClaim.Id" asp-page-handler="Delete"/>
            }
                
            <a class="btn btn-primary" asp-page="./AddUserRole" asp-route-userid="@Model.User.Id">Chỉnh sửa role cho user</a>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BigStore/Areas/Admin/Pages/Role/Index.cshtml
@page "/admin/role"
@model IndexModel
@{
    ViewData["Title"] = "Danh sách các role (vai trò)";
}
<h3>Danh sách các role</h3>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<a class="btn btn-primary" asp-page="./Create">Thêm mới Role</a>

<a class="btn btn-success" asp-page="./User">Gán role cho người dùng</a>

<table class="table">
    <tr>
    <th>Role ID</th>
    <th>Tên</th>
    <th>Tác vụ</th>
    </tr>
        @foreach (var role in @Model.Roles)
        {
            <tr>
            <td>@role.Id</td>
            <td>@role.Name
                @foreach(var claim in role.Claims)
                {
                    <small>@claim</small>
                }
            </td>
            <td>
                <a name="Input.ID" class="btn btn-success btn-sm" 
                    asp-page="./Edit" asp-route-roleid="@role.Id">Cập nhật Role</a>
                <a name="Input.ID" class="btn btn-danger btn-sm" 
                    asp-page="./Delete" asp-route-roleid="@role.Id">Xóa Role</a>
            </td>
            </tr>
        }
</table>

BigStore/Areas/Admin/Pages/Role/User.cshtml
@page "/admin/role/users/"
@model BigStore.Areas.Admin.Pages.Role.UserModel
@{
    ViewData["Title"] = "DANH SÁCH NGƯỜI DÙNG";
}

<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<table class="table table-striped">
    <tr>
        <th>UserName</th>
        <th>Roles</th>
        <th>Actions</th>
    </tr>
    @foreach (var user in @Model.users)
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.listroles</td>
            <td>
                <form method="POST" class="d-inline">
                <button name="Input.ID" value="@user.Id" class="btn btn-primary btn-sm" 
                        asp-page="./AddUserRole">Cập nhật Role</button>
                </form>
            </td>
        </tr>
        
    }
</table>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
@{

    Func<int?,string> generateUrl = (int? _pagenumber)  => {
        return Url.Page("./User", new {pageNumber = _pagenumber});
    };

    var datapaging = new {
        currentPage = Model.pageNumber,
        countPages  = Model.totalPages,
        generateUrl =  generateUrl
    };

}
<partial name="_Paging" model="@datapaging" />

BigStore/Areas/Admin/Pages/Role/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}